Makefile, run.sh, script.sh
<br/>
DB, Nest 관련 Makefile 작성
<br/>
스크립트 파일로 진행했었는데, 여러모로 불편해서 Makefile의 필요성을 느꼈습니다.
<br/>
<br/>
<br/>
=> 13 feature 개발용 db 폴더 추가 makefile 추가

prisma/migrations/20230412093203_init/migration.sql, prisma/schema.prisma, prisma/seed.ts
<br/>
GameWatch ERD 수정
<br/>
중복된 데이터가 2개씩 생기는 것 같아서 하나만 생기도록 수정함
<br/>
<br/>
<br/>
=> refactor: GameWatch ERD 수정

docker-compose.yml, package-lock.json, package.json, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/auth/dto/OAuthUserInfo.dto.ts, src/auth/dto/index.ts, src/auth/guard/auth.guard.ts, src/auth/jwt/jwt.util.ts, src/auth/repository/auth.repository.ts
- [X ] commit message 가 적절한지 확인해주세요.
- [X ] Assignees, Label 을 붙여주세요.
<br/>
<br/>
- 인증 기능 구현
<br/>
closes: #19 
- protected Url 만들어서 로그인 후 접속
<br/>
<br/>
=> Feature/18 feature oauth/JWT/AuthGuard 기능 개발

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/jwt/jwt.util.ts
<br/>
jwt 토큰 발행 시 제한 시간을 안 두어서 1시간으로 설정
<br/>
jwt 토큰 발행 시 제한 시간을 안 두어서 1시간으로 설정
<br/>
토큰을 30초를 둔 후에 30초 전 후로 테스트함
제대로 토큰이 30초 안에 만료됩니다
<br/>
<br/>
=> feat: jwt token 만료 1시간으로 설정

src/channels/channels.controller.ts
<br/>
- request 타입 지정 및 아이디 추출
<br/>
- request 타입 지정되어있지 않아 추가함.
<br/>
closes: #36 
<br/>
<br/>
=> refactor: request 타입 지정 및 아이디 추출

src/auth/repository/auth.repository.ts
유저가 최초 로그인 후에 이미지를 바꿀 수 있기 때문에
Issues: #이슈번호
Resolves: #이슈번호
<br/>
🚑Oauth에 최초 로그인 할 경우에만 이미지 DB에 넣는 것으로 변경
<br/>
사용자가 최초 로그인 후에 사진을 변경할 수 있게 하기 위해서
<br/>
closes: #35
테스트는 안 했습니다
<br/>
<br/>
=> fix: 🚑Oauth에 최초 로그인 할 경우에만 이미지 DB에 넣는 것으로 변경

src/channels/channels.module.ts, src/games/events/game.gateway.ts, src/games/games.service.ts
<br/>
Game API 예외 처리 로직 수정
<br/>
- (userGameIds === null) 부분 삭제 -> 불필요한 처리였음
- buyGame 메서드에서 해당 userid, gameid의 userGame이 존재하는지 먼저 확인 -> 중복 체크
<br/>
- userGame 중복 생성 막기
- findMany는 매칭되는 결과가 없으면 빈배열([])을 반환
<br/>
<br/>
=> Refactor/46 refactor game api 예외 처리 로직 수정

src/friends/friends.controller.ts, src/friends/friends.service.ts, src/friends/repository/friends.repository.ts, src/friends/repository/friends.type.ts
<br/>
friend api - buddyId 대신 friendId 사용
<br/>
- 
<br/>
closes: #43 
<br/>
<br/>
=> fix: use friendId instead of buddyId

src/channels/channels.controller.ts, src/channels/channels.service.ts, src/channels/repository/channels.repository.ts
<br/>
- 채널에서 관리자를 설정해주는 기능을 추가
- 차후 관리자 해제를 위해 true false 로 확장성있는 코드로 작성함.
<br/>
- 채널 오너가 관리자를 설정해주는 기능 추가. 다만 한번 관리자로 설정되면 채널을 떠나기까지 계속 관리자로 남아 있음.
<br/>
closes: #44 
- API를 POSTMAN으로 요청 후 디비 저장 데이터 변경 됐는지 체크
<br/>
<br/>
=> Feature/44 관리자 설정 api

src/account/account.controller.ts, src/account/account.module.ts, src/account/account.service.ts, src/account/repository/account.repository.ts, src/account/repository/account.type.ts, src/app.controller.ts, src/app.module.ts, src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/channels/channels.module.ts, src/friends/friends.module.ts, src/games/events/game.gateway.ts, src/games/games.controller.ts, src/games/games.module.ts, src/games/games.service.ts, src/games/repository/games.repository.ts
<br/>
- auth 2차 인증
- Account API
마이 페이지(getMyPage)
유저 프로필 업데이트(updateUserProfile)
- 여태까지 하면서 타입 안넣었던 것들 추가
<br/>
<br/>
```{
"user": {
"nickname": "update nickname jinhokim yeah",
"intraId": "jinhokim",
"image": "test/image",
"phoneNumber": null,
"email": "jinhokim@student.42seoul.kr"
},
"userGame": [
{
"game": {
"gameId": "51e26897-4b9a-4bb3-9963-35e74609d4ab",
"name": "핑퐁핑퐁"
},
"gameHistory": {
"wincounts": 2,
"loseCounts": 1
}
},
{
"game": {
"gameId": "ddebccab-7775-4ee8-8e40-f682e4b5d468",
"name": "테트리스"
},
"gameHistory": null
},
{
"game": {
"gameId": "0813bcba-311d-4c4f-b299-d82797b59682",
"name": "퍼즐팡팡"
},
"gameHistory": null
},
{
"game": {
"gameId": "b8a96be2-c579-4982-adfb-16e32ef7ccf7",
"name": "좀비좀비"
},
"gameHistory": null
}
]
}
```
입력
```{
"nickname": …
```
=> Feature/49 feature auth 2차 인증과 Account API

src/friends/friends.controller.ts, src/friends/friends.service.ts, src/friends/repository/friends.repository.ts, src/friends/repository/friends.type.ts
<br/>
친구 상세 페이지에 필요한 API 작성
<br/>
- 친구 정보 및 필요 게임 정보 프론트엔드 구현에 필요
<br/>
closes: #52 
- POSTMAN 테스트
<br/>
<br/>
=> feature/52 friendId info tatils

src/channels/channels.service.ts, src/channels/repository/channels.repository.ts
<br/>
채널 목록에서 최신 메시지 시간 표시 로직에서 채팅 기록 없는 경우에 대한 수정
- 채널 생성 시 fake message를 chat 테이블에 생성
- 채팅 로그 불러올 때 fake message 제외하고 반환
- 채널 목록의 각 채널의 최신 메시지 시간 표시에서 채팅 기록 없는 경우 fake message 생성 시간으로 반환
<br/>
- 채널 목록에서 최신 메시지 시간 표시할 때 마지막 채팅 시간을 보여주는 로직에서 만약 채팅 내역이 아무것도 없을 경우에 대하여 해결하기 위함.
<br/>
closes: #59 
- postman에서 테스트
<br/>
<br/>
=> Feature/#59 refactor 채널 목록에서 최신 메시지 시간 표시 로직에서 채팅 기록 없는 경우에 대한 수정

prisma/schema.prisma, src/friends/dto/friends.dto.ts, src/friends/friends.controller.ts, src/friends/friends.service.ts, src/games/dto/games.dto.ts, src/games/repository/game.type.ts, src/games/repository/games.repository.ts
<br/>
친구의 게임 전적을 보여주는 API 구현
게임히스토리 테이블에 create_at 추가
<br/>
백엔드 API 개발
<br/>
포스트맨에서 테스트
<br/>
<br/>
=> Feature/38 백엔드 api 개발: 친구 게임 전적 보기 API 구현

Makefile, package-lock.json, package.json, src/account/account.controller.ts, src/account/account.service.ts, src/account/repository/account.repository.ts, src/account/repository/account.type.ts, src/app.controller.ts, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/templates/verification.ejs
<br/>
이미지 저장, 업로드 기능
- 초기 로그인 때 인트라 이미지를 서버에 저장, db에도 이미지 경로 저장
- 프로필 수정 -> 이미지 업로드 기능 구현
<br/>
<br/>
- 초기 로그인 시 인트라 프로필 이미지가 서버에 잘 저장되는지 확인  
이미지 경로: assets/images/  
- 프로필 수정시 서버의 이미지가 수정되는 지 확인  
- 프로필 수정한 이후인데도 로그인할 때 마다 다시 인트라 이미지로 덮어지지는 않는지 확인  
<br/>
<br/>
=> Feature/62 feature 초기 intra 이미지 저장과 이미지 업로드 구현

src/auth/guard/auth.guard.ts, src/channels/events/channels.gateway.ts
<br/>
http 통신처럼 소켓에서도 useGuard 사용하여 토큰 검증 및 userId 추출
- channel 소켓에 useGuard 적용
<br/>
- 이러한 이유 때문에 변경했습니다!
<br/>
closes: #60 
<br/>
<br/>
=> refactor: channel의 소켓 통신에 useguard 추가

src/channels/channels.controller.ts, src/channels/channels.service.ts
<br/>
채널 생성 api에서 채널 생성 후 채널 들어갈 때 필요한 channelId 반환하는 로직 추가
<br/>
- 채널 생성 api에서 채널 생성 후 채널 들어갈 때 필요한 channelId 반환하는 로직 추가
<br/>
closes: #66 
<br/>
<br/>
=> refactor: add reponse data for create channel api

src/account/events/account.gateway.ts, src/auth/repository/auth.repository.ts, src/games/events/game.gateway.ts, src/games/games.service.ts, src/games/repository/game.type.ts, src/games/repository/games.repository.ts
<br/>
소켓 통신 코드에 useguard 추가
- account 소켓 통신
- game 소켓 통신
<br/>
- 소켓 통신에서도 토큰 검증을 위해 추가
<br/>
closes: #60 
<br/>
<br/>
=> Feature/#60 refactor [account, game] 소켓 useguard 추가

src/account/dto/account.dto.ts, src/account/events/account.gateway.ts, src/auth/dto/auth.dto.ts, src/auth/repository/auth.repository.ts, src/channels/channels.controller.ts, src/channels/channels.service.ts, src/channels/dto/channels.dto.ts, src/friends/dto/friends.dto.ts, src/friends/friends.controller.ts, src/games/dto/games.dto.ts, src/games/events/game.gateway.ts, src/games/games.controller.ts, src/games/games.service.ts, src/games/repository/game.type.ts, src/games/repository/games.repository.ts
<br/>
api path variable의 id의 데이터가 UUID인지 체크
<br/>
- uuid가 아닌 데이터가 path variable로 들어올 경우 유효성 검사
<br/>
closes: #69 
<br/>
<br/>
=> Feature/#69 refactor api path variable의 id의 데이터가 UUID인지 체크

package-lock.json, package.json, src/account/account.controller.ts, src/account/account.module.ts, src/account/account.service.ts
<br/>
- ServeStaticModule 을 사용해서 정적 파일을 보낼 수 있도록 함
- userId(Query)로 유저 이미지를 반환하는 getUserImageByUserId 메서드 추가함
<br/>
- 지금 메서드들이 이미지의 경로를 받는데 단순 string이라 사용을 할 수가 없기에
이미지를 넘겨주는 api를 추가함
<br/>
- 유저 이미지 임의로 저장해놓고, 유저 아이디에 맞게 이미지가 넘어오는 지 확인함
<br/>
<br/>
=> feat: 정적 이미지 반환 메서드 추가

src/account/repository/account.repository.ts, src/account/repository/account.type.ts
<br/>
getMyPage에 메서드에서 userId도 같이 보내도록 수정함
<br/>
마이 페이지에서 아직 userId를 알 방법이 없었음. 나중에는 recoil로 기억해서 사용하는 것도 좋을 것 같다
<br/>
userId도 같이 잘 넘어옴 
<br/>
<br/>
=> feat: 마이 페이지를 위해 userId도 같이 보냄

src/channels/channels.service.ts
<br/>
매개변수 순서 수정
<br/>
<br/>
<br/>
<br/>
=> refactor: 매개변수 순서 수정

src/account/account.controller.ts
<br/>
무엇을 합니다!
프로필 수정 api를 이미지, 닉네임 수정 2개로 나눔
<br/>
지금 프론트에서 유저 이미지와 닉네임을 한번에 같이 보내는데, 둘다 왔거나 이미지가 안왔을 때는 괜찮은데
이미지가 안왔을 때의 처리를 실패함.
<br/>
이미지와 닉네임 각각 잘 업데이트 되는 것을 확인함
<br/>
<br/>
=> fefact: 프로필 수정 api를 2개로 나눔. 이미지와 닉네임

src/channels/channels.service.ts, src/channels/events/channels.gateway.ts, src/channels/events/events.type.ts
<br/>
채팅 수신 객체에 isAdmin, time 추가
<br/>
- 
<br/>
<br/>
<br/>
=> Feature/채팅 수신 객체에 isAdmin, time 추가

src/account/account.service.ts
<br/>
hotfix
<br/>
hotfix
<br/>
hotfix
<br/>
<br/>
=> feat: update user nickname

src/channels/repository/channels.repository.ts
<br/>
무엇을 합니다!
-  공개채널 페이지 GET API 약간 수정
<br/>
- 비밀번호 여부 필요
<br/>
- 프론트에서 확인
<br/>
<br/>
=> feat:API 수정

src/channels/channels.service.ts
<br/>
time이 안 들어올 때 null일경우 고려 예외처리
<br/>
- 클라이언트에서 요청 시 서버 다운됨
<br/>
closes: #84 Issue Number
- 클라에서 다시 요청해보고 정상작동 확인
<br/>
<br/>
=> fix: 버그 수정

src/account/account.service.ts, src/account/repository/account.type.ts, src/games/games.controller.ts
<br/>
- 게임 히스토리의 wincounts -> winCount, loseCounts -> loseCount로 수정
- 게임 컨트롤러에서 param으로 gameId를 받는데, dto로 { gameId: string}으로 받고 있었어서 에러나는 부분 수정
<br/>
- 게임 히스토리에 오타(wincounts)가 있었음
- 게임 컨트롤러에서 파라미터를 잘못 받아서 에러가 났었음. 파이프 수정하기 전에 짜서 몰랐던 것 같음
<br/>
- 게임 api들 정상 동작
<br/>
<br/>
=> Refactor/86 refactor 게임 히스토리 변수명 수정 게임 컨트롤러 부분 오류 수정

src/account/account.service.ts
<br/>
- 닉네임 중복 처리 기능을 안 넣어서 추가했습니다
<br/>
- 프로필 수정 모달에서 닉네임 중복 처리 기능을 넣는 것을 깜빡해서 서버가 터짐
<br/>
- 수정 요청한 닉네임이 이미 있을 경우 에러 처리가 잘 되는 것을 확인함
<br/>
<br/>
=> fix: 닉네임 중복 처리

src/account/account.controller.ts, src/app.controller.ts, src/auth/auth.controller.ts
<br/>
유저 정보 api 추가 & 유저 인증 수정
<br/>
- 
<br/>
closes: #90 
<br/>
<br/>
=> refactor: 유저 정보 api 추가 & 유저 인증 수정

src/account/events/account.gateway.ts
<br/>
로그인할 때 사용자 정보 조회 에러 처리 추가
<br/>
로그인할 때 사용자 정보 조회 에러 처리 추가
<br/>
<br/>
<br/>
=> refactor: 에러 처리 추가

src/channels/channels.service.ts, src/channels/repository/channels.repository.ts, src/channels/repository/channels.type.ts
<br/>
- 채팅방 멤버 가져오는 api에서 isfriend가 항상 false인 버그를 수정
- 채팅방 멤버 가져오는 api에서 intraId도 가져오도록 추가함
<br/>
프론트에서 intraId가 필요했음
<br/>
- 친구 관계가 올바르게 반환됨
<br/>
<br/>
=> Bug/96 bug 채팅방 멤버 가져오는 api에서 isfriend가 항상 false인 버그를 수정

src/games/events/game.gateway.ts
<br/>
무엇을 합니다!
- 핑퐁 게임 백엔드 로직 추가
<br/>
- 핑퐁 게임 백엔드 로직 추가, 백엔드에서 공 위치 패들 위치 계산해서 프론트로 다시 쏴줌.
<br/>
- 게임 해봄
<br/>
<br/>
=> Feature/94 게임 소켓 플레이

src/games/events/game.gateway.ts
<br/>
- 버그 수정
<br/>
- 핑퐁 게임 위치 버그 조정
<br/>
closes: #99 
- 게임 테스트
<br/>
<br/>
=> bug: 핑퐁 게임 위치 조정

src/account/events/account.gateway.ts, src/auth/auth.controller.ts, src/auth/auth.service.ts, src/games/games.module.ts
<br/>
- 게임 초대 소켓 API(게임 초대, 초대 거절, 초대 수락, 초대 취소)
<br/>
- gamesService export  -> accuonts에서 써야 해서
<br/>
- 게임 초대, 초대 수락, 거절, 취소 잘 동작함
- 에러 처리 잘 되는 것 같음
<br/>
<br/>
=> Feature/101 feature 게임 초대 소켓 구현

src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts, src/games/games.module.ts
<br/>
- 핑퐁 코드 리팩토링/ 로직 분리
<br/>
- game.gateway.ts가 너무 복잡해져서 기능 분리
<br/>
closes: #104 Issue Number
- 게임 테스트
<br/>
<br/>
=> Refactor/104 핑퐁 로직 분리

src/friends/friends.controller.ts
<br/>
친구 조회 url 수정
<br/>
- 친구 목록 조회 url과 친구 조회 url 중복
<br/>
closes: #106 
- 
<br/>
<br/>
=> bug: 친구 조회 url 수정

src/friends/friends.controller.ts, src/friends/friends.service.ts
<br/>
친구가 아닌 경우 고려
<br/>
- 친구가 아닌 경우 고려
<br/>
closes: #109 
- 
<br/>
<br/>
=> refactor: 친구가 아닌 경우 고려

src/channels/channels.service.ts, src/channels/repository/channels.repository.ts
<br/>
디엠일 때 채팅방 이름 추출 & 이전에 dm방을 나갔다가 다시 들어간 경우
<br/>
- 
<br/>
closes: #112 
- 
<br/>
<br/>
=> refactor: 디엠일 때 채팅방 이름 추출 & 이전에 dm방을 나갔다가 다시 들어간 경우

package-lock.json, package.json, src/account/events/account.gateway.ts, src/app.module.ts, src/games/events/game.gateway.ts, src/games/games.controller.ts, src/games/games.service.ts
<br/>
게임 초대 -> 게임 준비로 이어지는 로직 구현
<br/>
<br/>
게임 소켓에서 게임 준비가 취소 되었을 때 로그인 소켓의 유저 정보들도 online으로 업데이트 해줌
<br/>
<br/>
=> Feature/103 feature 게임 준비 방 생성

src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts
<br/>
- 게임 점수 승패 셋업 (소켓 연결 매칭 합치기 전)
<br/>
- 유저 매칭 후 승패 저장을 위한 코드수정
<br/>
<br/>
<br/>
=> Feature/111 게임 승패 기록

src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts
<br/>
무엇을 합니다!
- 매칭 후 상황에서 게임 플레이 디비 저장
<br/>
<br/>
closes: #116 Issue Number
<br/>
<br/>
=> Feature/116 매칭유저 게임 연결

src/games/dto/games.dto.ts, src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts
<br/>
- 백엔드 코드에 맵으로 gamewatchid 별로 게임 인포 관리
<br/>
- 다중 게임 플레이를 관리하기 위한 코드 수정
<br/>
closes: #123 Issue Number
- 게임 플레이 해봄.
<br/>
<br/>
=> Feature/123 멀티 게임룸

src/channels/channels.controller.ts, src/channels/channels.service.ts
<br/>
isMute와 isAdmin 조회
<br/>
- 
<br/>
closes: #129 
- 
<br/>
<br/>
=> refactor: isMute와 isAdmin 조회

src/games/dto/games.dto.ts, src/games/events/game.gateway.ts
<br/>
다중 게임 실시간 렌더링 버그 수정 -> 내일 전체적으로 코드 정리
<br/>
다중 게임 렌더링 구현
<br/>
4명이서 둘둘 각자 플레이 끊기지 않고 병렬로 잘 돌아가는 것 같음
<br/>
<br/>
=> Bug/126 bug 다중 게임 실시간 렌더링 안됨 버그

src/account/events/account.gateway.ts, src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts, src/games/games.service.ts
<br/>
무엇을 합니다!
- 게임 관전 및 관전자수 관리
- GG 버튼 기능은 없음
<br/>
- 게임 관전 기능 추가
<br/>
closes: #132 Issue Number
- 관전 테스트
<br/>
<br/>
=> Feature/132 게임 관전 로직

prisma/seed.ts, src/channels/channels.service.ts
<br/>
seed 수정 및 fake message 시간 수정
<br/>
- seed 수정 및 fake message 시간 수정
<br/>
closes: #133 
- 
<br/>
<br/>
=> seed 수정 및 fake message 시간 수정

src/auth/guard/auth.guard.ts, src/channels/channels.service.ts, src/channels/events/channels.gateway.ts
<br/>
채팅 에러 메시지 변경
<br/>
- 채팅 에러 메시지 변경
<br/>
closes: #138 
- 
<br/>
<br/>
=> refactor: 채팅 에러 메시지 변경

src/channels/channels.service.ts, src/channels/events/channels.gateway.ts, src/channels/repository/channels.repository.ts
<br/>
킥 당한 유저의 소켓 연결 해제 시 에러
<br/>
- 킥 당한 유저의 소켓 연결 해제 시 에러 해결
<br/>
closes: #140 
- 
<br/>
<br/>
=> Bug/140 bug 킥 당한 유저의 소켓 연결 해제 시 에러

src/channels/channels.controller.ts, src/channels/channels.service.ts, src/channels/events/channels.gateway.ts
<br/>
킥 소켓 사용
<br/>
- 킥 소켓 사용
<br/>
closes: #144 
<br/>
<br/>
=> bug: 킥 소켓 사용

src/friends/friends.controller.ts
<br/>
parseuuid 추가
<br/>
- parseuuid 추가
<br/>
closes: #146 
<br/>
<br/>
=> refactor: parseuuid 추가

src/games/games.controller.ts, src/games/games.service.ts, src/games/repository/games.repository.ts
<br/>
- 게임 컨트롤러 init 될 때 게임들 시딩하기(이미 게임들 시딩된 상태면 동작안함)
<br/>
- 도커에서 시딩이 쉽지가 않음
<br/>
- 초기에 game controller init될 때 game이 다 잘 들어감
- 이미 게임들 들어있을 땐 동작 안함
<br/>
<br/>
=> Feature/148 feature 게임 컨트롤러 init 될 때 게임들 시딩하기(이미 게임들 시딩된 상태면 동작안함)

src/account/dto/account.dto.ts, src/account/events/account.gateway.ts, src/app.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/auth/templates/verification.ejs, src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts, src/games/games.service.ts
<br/>
- 인증 메일 양식 수정 및 console.log 제거
<br/>
- 인증 메일 양식 수정 및 console.log 제거
<br/>
<br/>
<br/>
=> refactor: 인증 메일 양식 수정 및 console.log 제거

src/channels/channels.service.ts, src/channels/events/channels.gateway.ts
<br/>
채팅 소켓 에러 메시지 분리
<br/>
- 채팅 소켓 에러 메시지 분리
<br/>
closes: #151 
<br/>
<br/>
=> Refactor/151 refactor 채팅 소켓 에러 메시지 분리

src/account/events/account.gateway.ts, src/games/games.service.ts
<br/>
랜덤 매칭 에러
<br/>
- 랜덤 매칭 에러
<br/>
closes: #154 
<br/>
<br/>
=> bug: 랜덤 매칭 에러

Makefile, src/games/events/game.gateway.ts
<br/>
- 상대방이 오프라인 상태인 경우의 처리
<br/>
- 상대방이 오프라인 상태인 경우의 처리
<br/>
- 상대방이 나갔을 때 동작하지 않고 전 페이지로 리다이랙션됨
<br/>
<br/>
=> Bug/156 bug 게임 상대방이 오프라인 상태인 경우의 처리

src/app.controller.ts, src/auth/auth.controller.ts, src/auth/auth.service.ts
<br/>
127.0.0.1 로컬로 설정된 것 env로 변경
<br/>
127.0.0.1 로컬로 설정된 것 env로 변경
<br/>
closes: #159 
직접 실행해서 로그인해서 Auth 검증
<br/>
<br/>
=> fix: 127.0.0.1 로컬로 설정된 것 env로 변경

src/account/account.service.ts, src/account/repository/account.repository.ts, src/auth/auth.controller.ts, src/channels/channels.controller.ts, src/channels/events/channels.gateway.ts, src/channels/repository/channels.repository.ts, src/friends/friends.controller.ts, src/friends/repository/friends.repository.ts, src/games/events/game.gateway.ts, src/games/gameplays/pingpong.service.ts, src/games/games.service.ts, src/games/repository/games.repository.ts
<br/>
게임 오류 및 await 추가
<br/>
- 게임 오류 및 await 추가
<br/>
closes: #161 
<br/>
<br/>
=> bug: 게임 오류 및 await 추가

src/auth/auth.service.ts, src/games/games.service.ts
<br/>
콘솔 로그 주석 처리
<br/>
- 콘솔 로그 주석 처리
<br/>
closes: #164 
<br/>
<br/>
=> chore: 콘솔 로그 주석 처리

src/channels/channels.service.ts
<br/>
채널 API에서 리스트 여러 번 요청하는 것에 대해서 예외처리
<br/>
배포 전 버그 발생
<br/>
closes: #166 
직접 실행해서 테스트
<br/>
<br/>
=> fix: 채널 리스트 여러번 요청하는 것에 대해서 예외처리

src/games/events/game.gateway.ts, src/games/repository/game.type.ts
<br/>
gamewatchid 없는 방 들어갔을 때 처리 및 playgame쪽 any 수정
<br/>
- gamewatchid가 없는데도 들어가져서 게임 초기 화면이 나왔었음
- any타입 수정
<br/>
<br/>
<br/>
=> Refactor/171 refactor gamewatchid 없는 방 들어갔을 때 처리 및 playgame쪽 any 수정

src/channels/channels.service.ts, src/channels/repository/channels.repository.ts, src/channels/repository/channels.type.ts
<br/>
내가 속한 채널 목록 페이지의 오너 정보 전달
<br/>
- 내가 속한 채널 목록 페이지의 오너 정보 전달
<br/>
closes: #175 
<br/>
<br/>
=> refactor: 내가 속한 채널 목록 페이지의 오너 정보 전달
